name: Frontend code-analysis on branches

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "frontend/**"

jobs:

  codeanalysis:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v4

      - name: Linting
        run: |
          make install-frontend
          make lint-frontend

  unit:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Test
        run: |
          make install-frontend
          make test-frontend-ci
