name: Redeploy 'latest' image tags to testing.ploneconf.org

on:
  workflow_dispatch:

jobs:

  deploy:
    if: github.event_name == 'workflow_dispatch'
    concurrency: deploy_testing
    runs-on: ubuntu-latest
    environment:
      name: testing.ploneconf.org
      url: https://testing.ploneconf.org
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to cluster
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_GHCR_READ_TOKEN }}
          remote_host: ${{ vars.DEPLOY_HOST }}
          remote_port: ${{ vars.DEPLOY_PORT }}
          remote_user: ${{ vars.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: devops/stacks/testing.ploneconf.org.yml
          stack_name: testing-ploneconf-org
          stack_param: ${{ github.ref_name }}
          env_file: ${{ secrets.ENV_FILE }}
          deploy_timeout: 480
